var enemy = {
	monsterList: {},
	joustmite: {
		name: "Joustmite",
		display: "<^)",
		hp: 2000,
		attack: 3,
		status: "rock",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	slooch: {
		name: "Pyroclasmic Slooch",
		display: "/\\~",
		hp: 1000,
		attack: 4,
		status: "",
		halfAtk: "red",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	blowhog: {
		name: "Fiery Blowhog",
		display: "-{}",
		hp: 1000,
		attack: 6,
		status: "fire",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	amprat: {
		name: "Bearded Amprat",
		display: "m()",
		hp: 1500,
		attack: 6,
		status: "",
		halfAtk: "yellow",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	anodeBeetle: {
		name: "Anode Beetle",
		display: "nHn",
		hp: 500,
		attack: 100,
		status: "electric",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	sheargrub: {
		name: "Sheargrub",
		display: ">ww",
		hp: 500,
		attack: 2,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	snagret: {
		name: "Snagret",
		display: "_/|",
		hp: 2800,
		attack: 6,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: "evasive"
	},
	cannonBeetle: {
		name: "Cannon Beetle",
		display: "(o)",
		hp: 4000,
		attack: 12,
		status: "rock",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	wollywog: {
		name: "Wollywog",
		display: "p@q",
		hp: 1100,
		attack: 4,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	goolix: {
		name: "Goolix",
		display: "C%J",
		hp: 5000,
		attack: 15,
		status: "water",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	bulbear: {
		name: "Bulbear",
		display: "=&%",
		hp: 1300,
		attack: 5,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	skutterchuck: {
		name: "Skutterchuck",
		display: "-M>",
		hp: 2000,
		attack: 5,
		status: "",
		halfAtk: "rock",
		extraDmgFrom: "rock",
		extraDmgTo: "",
		special: ""
	},
	arachnode: {
		name: "Arachnode",
		display: "30E",
		hp: 700,
		attack: 2,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "pink",
		special: ""
	},
	cannonLarva: {
		name: "Armored Cannon Larva",
		display: ",@,",
		hp: 2000,
		attack: 5,
		status: "rock",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	crawbster: {
		name: "Segmented Crawbster",
		display: "7G>",
		hp: 3000,
		attack: 15,
		status: "",
		halfAtk: "rock",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	mawdad: {
		name: "Armored Mawdad",
		display: "=Oo",
		hp: 8000,
		attack: 5,
		status: "",
		halfAtk: "",
		extraDmgFrom: "rock",
		extraDmgTo: "",
		special: ""
	},
	snitchbug: {
		name: "Swooping Snitchbug",
		display: "~O~",
		hp: 2400,
		attack: 1,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: "evasive"
	},
	groink: {
		name: "Gatling Groink",
		display: "-(O",
		hp: 2200,
		attack: 6,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	bulblax: {
		name: "Empress Bulblax",
		display: "oOo",
		hp: 5000,
		attack: 11,
		status: "",
		halfAtk: "rock",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	sputtlefish: {
		name: "Sputtlefish",
		display: "%O{",
		hp: 900,
		attack: 3,
		status: "",
		halfAtk: "white",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	phosbat: {
		name: "Vehemoth Phosbat",
		display: "&#60;O>",
		hp: 4000,
		attack: 9,
		status: "",
		halfAtk: "white",
		extraDmgFrom: "yellow",
		extraDmgTo: "",
		special: ""
	},
	poisonWall: {
		name: "Poisoned Bramble Wall",
		display: "<i>TXT</i>",
		hp: 5000,
		attack: 100,
		status: "poison",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	electricWall: {
		name: "Electric Gate",
		display: "NMN",
		hp: 5000,
		attack: 100,
		status: "electric",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	rockWall: {
		name: "Reinforced Wall",
		display: "|||",
		hp: 3000,
		attack: 0,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: "bomb"
	},
	dirtWall: {
		name: "Dirt Wall",
		display: "Y#Y",
		hp: 10000,
		attack: 0,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	basicWall: {
		name: "Bramble Wall",
		display: "TXT",
		hp: 10000,
		attack: 0,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	},
	bulborb: {
		name: "Bulborb",
		display: ">%%",
		hp: 700,
		attack: 3,
		status: "",
		halfAtk: "",
		extraDmgFrom: "",
		extraDmgTo: "",
		special: ""
	}
};